name: CI/CD Allure

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run tests
        run: |
          mvn clean test \
          -Dauth.password=${{ secrets.AUTH_PASSWORD }} \
          -Dauth.client.secret=${{ secrets.AUTH_CLIENT_SECRET }}

      - name: Restore Allure history
        if: github.ref == 'refs/heads/master'
        run: |
          git clone --depth=1 --branch gh-pages https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} gh-pages || true
          mkdir -p target/allure-results/history
          cp -r gh-pages/history/* target/allure-results/history || true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Publish Report
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages